--- 
- !ruby/object:Product 
  last_buy_date: 2009-11-13 17:59:26.734000 +00:00
  name: Milk
  description: semi-skimmed milk
- !ruby/object:Product 
  last_buy_date: 2009-11-13 17:59:26.734000 +00:00
  name: Butter
  description: ""
- !ruby/object:Product 
  last_buy_date: 2009-11-13 17:59:26.734000 +00:00
  name: Chocolate
  description: Belgian chocolate
- !ruby/object:Product 
  last_buy_date: 2009-11-13 17:59:26.734000 +00:00
  name: Cola
  description: ""
- !ruby/object:Product 
  last_buy_date: 2009-11-13 17:59:26.734000 +00:00
  name: Sugar
  description: ""
- !ruby/object:Product 
  last_buy_date: 2009-11-13 17:59:26.734000 +00:00
  name: Marmalade
  description: ""
- !ruby/object:Product 
  last_buy_date: 2009-11-13 17:59:26.734000 +00:00
  name: Cookies
  description: ""
- !ruby/object:Product 
  last_buy_date: 2009-11-13 17:59:26.734000 +00:00
  name: Water
  description: sparkling water
- !ruby/object:Product 
  last_buy_date: 2009-11-13 17:59:26.734000 +00:00
  name: Fish
  description: salmon
- !ruby/object:Product 
  last_buy_date: 2009-11-13 17:59:26.734000 +00:00
  name: Ham
  description: ""
- !ruby/object:Product 
  last_buy_date: 2009-11-13 17:59:26.734000 +00:00
  name: Bread
  description: ""
- !ruby/object:Product 
  last_buy_date: 2009-11-13 17:59:26.750000 +00:00
  name: Spaghetti
  description: ""
- !ruby/object:Product 
  last_buy_date: 2009-11-13 17:59:26.750000 +00:00
  name: Yogurt
  description: plain
- !ruby/object:Product 
  last_buy_date: 2009-11-13 17:59:26.750000 +00:00
  name: Jam
  description: strawberry
- !ruby/object:Product 
  last_buy_date: 2009-11-13 17:59:26.750000 +00:00
  name: Cereals
  description: Description for cereals
