require 'rubygems'
require 'rake/gempackagetask'
 
spec = Gem::Specification.new do |s| 
  s.name = "swiby"
  s.version = "1.0.0"
  s.author = "Jean Lazarou"
  s.email = "ruby @at@ alef1.org"
  s.homepage = "http://alef1.org/swiby/"
  s.platform = Gem::Platform::RUBY
  s.summary = "Ruby GUI framework using Java/Swing with jruby"
  s.files = FileList["{bin,lib,samples,demo}/**/*"].to_a
  s.require_path = "lib"
  s.autorequire = "swiby"
  s.test_files = FileList["{test}/**/*test.rb"].to_a
  s.has_rdoc = true
  s.extra_rdoc_files = ["LICENSE.txt"]
  s.default_executable = 'sweb'
  s.executables = ['sweb']
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_tar = true 
end

task :default => "pkg/#{spec.name}-#{spec.version}.gem" do
  puts "generated latest version"
end